### PR TITLE
Make sure to correctly record errors

### LINKED ISSUE #610: Fail the release when `go.mod` update fails
Sometimes it fails silently and continues the release, even though it clearly missed some dependencies.

For example (from https://github.com/submariner-io/releases/actions/runs/3748563589/jobs/6366039099):
```
[10:42:27.377] [submariner-operator]$ GOPROXY=direct go get github.com/submariner-io/submariner@v0.13.3
go: downloading github.com/submariner-io/submariner v0.13.3
go: downloading github.com/go-ping/ping v0.0.0-20210506233800-ff8be3320020
go: downloading github.com/vishvananda/netlink v1.1.1-0.20210518155637-4cb3795f2ccb
go: downloading golang.zx2c4.com/wireguard/wgctrl v0.0.0-20211215182854-7a385b3431de
go: downloading golang.zx2c4.com/wireguard v0.0.0-20211129173154-2dd424e2d808
go: downloading golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4
go: downloading github.com/vishvananda/netns v0.0.0-20200728191858-db3c7e526aae
go: downloading honnef.co/go/tools v0.2.2
go: downloading github.com/mdlayher/genetlink v1.1.0
go: downloading github.com/mdlayher/netlink v1.4.2
go: downloading github.com/josharian/native v0.0.0-20200817173448-b6b71def0850
go: downloading github.com/mdlayher/socket v0.0.0-20211102153432-57e3fa563ecb
go: downloading github.com/BurntSushi/toml v0.4.1
go: golang.zx2c4.com/wireguard@v0.0.0-20211129173154-2dd424e2d808 requires
	golang.zx2c4.com/go118/netip@v0.0.0-20211111135330-a4a02eeacf9d: unrecognized import path "golang.zx2c4.com/go118/netip": reading https://golang.zx2c4.com/go118/netip?go-get=1: 404 Not Found
[10:43:14.413] [submariner-operator]$ go mod tidy -compat=1.17
[10:43:14.837] [submariner-operator]$ go mod vendor
...
```

### PR DESCRIPTION
**Pull request by mkolesnik**
Using the `command || errors=...` syntax makes `errexit` and `pipefail` options moot, and any command run in this manner will continue running after failure (which could result in a 0 return code).

Make sure errors are recorded properly.

Resolves #610 

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
If errors stop the process immediately, is there any point in counting them?

**Comment by mkolesnik** [comment]
> If errors stop the process immediately, is there any point in counting them?

It helps to know as much as possible in this case, since this workflow is not transactional - eg you can't (simply) roll back all your changes.

Also some errors can be recoverable manually, eg bumping the shipyard/admiral/etc versions, so in these cases it makes sense to let the process proceed.

The easiest of course is to do nothing and let it trip up the entire workflow, but I don't think it has any benefit to us in this case.

**Comment by skitt** [comment]
> > If errors stop the process immediately, is there any point in counting them?
> 
> It helps to know as much as possible in this case, since this workflow is not transactional - eg you can't (simply) roll back all your changes.
> 
> Also some errors can be recoverable manually, eg bumping the shipyard/admiral/etc versions, so in these cases it makes sense to let the process proceed.
> 
> The easiest of course is to do nothing and let it trip up the entire workflow, but I don't think it has any benefit to us in this case.

But isn’t that what this PR does? `do-release.sh` will exit the first time it encounters an error.

**Comment by mkolesnik** [comment]
> But isn’t that what this PR does? `do-release.sh` will exit the first time it encounters an error.

Ah right that's a serious facepalm moment right there :facepalm: 

Hmm I'll have to find another way to implement this, unless you have a suggestion?

**Comment by skitt** [comment]
> > But isn’t that what this PR does? `do-release.sh` will exit the first time it encounters an error.
> 
> Ah right that's a serious facepalm moment right there facepalm
> 
> Hmm I'll have to find another way to implement this, unless you have a suggestion?

Perhaps a targeted fix would be appropriate: extract the `for project … update_dependencies` loop, and make it abort if it introduces errors (after completing, so we see all the dependency update errors for a given release).

File: scripts/do-release.sh [hunk 1]
```diff
@@ -10,6 +10,13 @@ set -o pipefail
 
 ### Functions: General ###
 
+# Run the supplied command in the background so that `errexit` and `pipefail` are honored.
```
Comment (skitt) [inline scripts/do-release.sh:13]:
```suggestion
# Run the supplied command in the background so that `errexit` and `pipefail` are ignored.
```

**Review by skitt — CHANGES_REQUESTED** [review]

File: scripts/do-release.sh (hunk 1 above)
Comment (skitt) [reply scripts/do-release.sh:13]: `pipefail` doesn’t matter anyway, because

    record_errors foo | bar

will record errors from `foo`, and the whole `record_errors foo` invocation will be piped; there’s no way to run

    record_errors 'foo | bar'

File: scripts/do-release.sh [hunk 2]
```diff
@@ -10,6 +10,13 @@ set -o pipefail
...
+# Errors will be counted instead of exiting immediately.
+function record_errors() {
+    "$@" &
+    wait $! || errors=$((errors+1))
```
Comment (skitt) [inline scripts/do-release.sh:17]: Why not

```suggestion
    "$@" || errors=$((errors+1))
```

**Review by skitt — CHANGES_REQUESTED** [review]

File: scripts/do-release.sh (hunk 2 above)
Comment (mkolesnik) [reply scripts/do-release.sh:17]: This is exactly the behavior causing the problem, e.g. this "succeeds" when it should fail:

```bash
bash -c 'set -e; foo() { doesnt_exist; echo STILL HERE $?; }; foo || echo Shouldve failed'
```

Whereas this works as we want:
```bash
bash -c 'set -e; foo() { doesnt_exist; echo STILL HERE $?; }; foo& wait $! || echo FAILED with $?'
```

File: scripts/do-release.sh (hunk 1 above)
Comment (mkolesnik) [reply scripts/do-release.sh:13]: Not that I mind changing documentation too much, but they were actually being ignored before this change, so having it as you suggest sounds confusing to me

File: scripts/do-release.sh (hunk 2 above)
Comment (skitt) [reply scripts/do-release.sh:17]: Ah yes, with functions.

File: scripts/do-release.sh (hunk 1 above)
Comment (skitt) [reply scripts/do-release.sh:13]: Right, it needs a little more explanation, since the settings are applied inside the command but don’t affect the `record_errors` function itself (*i.e.* a function called with `errexit` enabled will abort on error, but won’t caused `record_errors` to abort, thanks to the `||`). Given that running in the background specifically takes care of the former, we can leave the comment as-is.

**Review by skitt — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]
