### PR TITLE
Make sure to record failed "pin pull request"

### LINKED ISSUE #303: Handle failed attempts to pin PRs better
Currently after a release PR is merged the bot usually leaves a comment with additional PRs to review, which pin released projects to the version.
In case of failure (usually happens because something in the automated release process broke, but could be a transient failure) the comment will not have any clear indication that the failure happened, and instead will just have empty text where it was supposed to happen.

We should, instead, have the failure message in the comment so that the person driving the release is made aware of that failure.

It would also be good to either label the PR as failed (should be trivial) or perhaps open an issue assigned to the release driver to fix it.

### PR DESCRIPTION
**Pull request by mkolesnik**
Added a check to make sure if a "pin PR" is not created (for whatever
reason), the script will record the failure and also report it (and
consequently not try to enable auto merge on the PR).

Resolves: #303

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Review by Jaanki — APPROVED** [review]

File: scripts/do-release.sh [hunk 1]
```diff
@@ -88,7 +88,14 @@ function create_pr() {
     _git commit -a -s -m "${msg}"
     push_to_repo "${branch}"
     to_review=$(dryrun gh pr create --repo "${ORG}/${project}" --head "${branch}" --base "${base_branch}" --title "${msg}" \
-                --label "ready-to-test" --label "e2e-all-k8s" --body "${msg}")
+                --label "ready-to-test" --label "e2e-all-k8s" --body "${msg}" 2>&1)
+
+    # shellcheck disable=SC2181 # The command is too long already, this is more readable
+    if [[ $? -ne 0 ]]; then
```
Comment (dfarrell07) [inline scripts/do-release.sh:94]: I guess the other reasons the linter complains are related to avoiding potential bugs as the code changes in the future, not only readability:

* Since the command and its status test are decoupled, inserting an innocent command like echo "make finished" after make will cause the if statement to silently start comparing echo's status instead.
* Scripts that run or are called with set -e aka errexit will exit immediately if the command fails, even though they're followed by a clause that handles failure.

https://github-wiki-see.page/m/koalaman/shellcheck/wiki/SC2181

Comment (mkolesnik) [reply scripts/do-release.sh:94]: > I guess the other reasons the linter complains are related to avoiding potential bugs as the code changes in the future, not only readability:

That's also a valid concern, but readability is not insignificant.

> 
>     * Since the command and its status test are decoupled, inserting an innocent command like echo "make finished" after make will cause the if statement to silently start comparing echo's status instead.

True but we can be careful and bash programmers usually are aware of these pitfalls

> 
>     * Scripts that run or are called with set -e aka errexit will exit immediately if the command fails, even though they're followed by a clause that handles failure.

This doesn't happen in this case so it's not a problem for us, but should it happen we can fix it

> 
> 
> https://github-wiki-see.page/m/koalaman/shellcheck/wiki/SC2181

@skitt WDYT?

Comment (skitt) [reply scripts/do-release.sh:94]: I think SC2181 is moot, and not just because the command is too long. `$?` reflects the exit code of `dryrun gh pr create ...`, but the latter is run within a command substitution. This means that we can’t use an `if` construct directly with `if dryrun gh pr create ...`.

Comment (skitt) [reply scripts/do-release.sh:94]: So if there’s anything to fix, it’s the `disable=SC2181` comment ;-).

**Review by skitt — APPROVED** [review]

File: scripts/do-release.sh (hunk 1 above)
Comment (skitt) [reply scripts/do-release.sh:94]: Huh, scratch that, `if to_review=$(...)` would work, so the command length is the reason. (And fine by me.)

Comment (dfarrell07) [reply scripts/do-release.sh:94]: Okay, thanks @skitt and @mkolesnik.

**Review by dfarrell07 — APPROVED** [review]
